### PR TITLE
Adds search box to the VarLoader

### LINKED ISSUE #85: variable list in file is too messy
When opening a file the list of variables comes back in somewhat random order. Making it difficult to get to variable we need.

We shoud sort variables by number of dimensions (decreasing) and alphabetical next.

Also a quick search option the filter variables would be nice. E3SM for example as hundreds of variables to chose from.

### PR DESCRIPTION
**Pull request by sterlingbaldwin**
Fixes #85 

Doesnt add variable ordering, but the search is working.

### CODE REVIEW

**Comment by doutriaux1** [comment]
Load ing a climo E3SM file i get a pop up that says:
```
Command Error
Code resulted in errors. Error name: SyntaxError. Message: invalid syntax (<ipython-input-2-2be88889dc26>, line 2).

OK
```

And then:
```
Error
Code resulted in errors. Error name: SyntaxError. Message: invalid syntax (<ipython-input-2-2be88889dc26>, line 2).

OK
```

Also the variables are indeed sorted alphabetically (great) but in the old CDAT the used to be sorted first by number of dimensions. i.e $d variables, then 3D variables, then 2D variables.

Here for example variable: `CLD_CAL` show after variable `chla` even though `chla` is 2D and `CLD_CAL` is 3D.

**Comment by doutriaux1** [comment]
Otherwise I love the search button.

**Comment by sterlingbaldwin** [comment]
I noticed those errors as well. They have nothing to do with my changes, something is wonky with the vcs setup code that gets injected at startup.

**Comment by doutriaux1** [comment]
@downiec any idea what these are about?

**Comment by downiec** [comment]
@doutriaux1  I'm not sure where that error is coming from. I tested latest master and didn't get that error. Can you tell me where I can get the file you used?

**Comment by doutriaux1** [comment]
@downiec @sterlingbaldwin can we fix the conflict and merge this in please?

**Review by downiec — APPROVED** [review]

**Pull request merged**
