### PR TITLE
Vcdat2.0 sterling

### PR DESCRIPTION
**Pull request by sterlingbaldwin**
This is the very first pass at getting everything to work with notebooks instead of consoles. The one big difference here is that Notebooks are persistant, and right now it creates a new notebook every time you open a file. Consoles were nice in that they're just ephemeral things that disapear when you're done, but notebooks mean you have to do persistence and loading, none of which is included so far.

### CODE REVIEW

**Comment by sterlingbaldwin** [comment]
This is still pretty rough, but it will work for what Carlos needs to do in the demo video.

**Comment by doutriaux1** [comment]
thanks @sterlingbaldwin not sure I can get to a full review today (which menas before next monday) but I should be able to test it.

**Comment by doutriaux1** [comment]
@sterlingbaldwin is there a way to know the currently active notebook? If so that's what we need to use for injection. Also let's make a note right now, that each notebook will contain different `python` hence different variables and graphic methods, etc... So we will need to `refresh` the editors when we switch notebooks.

**Comment by sterlingbaldwin** [comment]
I completely agree @doutriaux1. I think there should be an option for creating a new notebook, or opening inside another notebook, or inside the currently active notebook. Right now Ive been launching the widget by double clicking on .nc files, but that doesnt have to be the only way to launch it, and it needs to be able to work with more then one notebook.

**Comment by sterlingbaldwin** [comment]
@downiec You should be able to use this branch to make a quick demo video for the F2F presentation.

**Comment by downiec** [comment]
I’ll try it out and send you the demo video when I’m done for feedback

**Comment by sterlingbaldwin** [comment]
ok two issues need to be fixed before this is merged, 1) the refresh button needs to be hooked up and added back in, 2) the buttons need to be fixed so they're horizontal instead of vertical. I can have this fixed by early this afternoon, which should still give Carlos enough time to record his demo video.

**Review by downiec — COMMENTED** [review]
I looked at it and tested it out. Seems good to me!

**Review by downiec — APPROVED** [review]

**Pull request merged**
