### PR TITLE
Vcdat2.0 sterling

### PR DESCRIPTION
**Pull request by sterlingbaldwin**
Fixes three issues:

1) When a user hits plot without first selecting a graphics method or template, uses the "default" for either instead of erroring.
2) After a plot has been run, the code that collected the variables/gms/templates would crash. This is because there was an assumption that the call to ```document.getElementsByClassName("jp-OutputArea-output")``` would return a single element array. Instead I changed it to collect the whole array, and just pop off the last element of it. This seams to have fixed the issue.
3) Removes the requirement to use vcs.js, and moves the call to an HTTP API call to the backend server extension.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@sterlingbaldwin quick original comments
In README seems like we lost the section about installing sidecar (pip install)
Looks like there's a lot of *useless* files `frontend/share/man` for example do we need these in repo?

**Comment by sterlingbaldwin** [comment]
I actually did a ```git rm -rf frontend``` to remove those files, they're still showing up for you?

**Comment by sterlingbaldwin** [comment]
the setup.py runs ```pip install sidecar```

**Comment by doutriaux1** [comment]
@sterlingbaldwin I forgot I did the `sidecar` thing....

**Comment by doutriaux1** [comment]
@sterlingbaldwin ok... that is actually what the PR says "file deleted"...

**Review by doutriaux1 — APPROVED** [review]
pushed 2 additions to env install (pip and nb_conda)

Tested it and it works fine (sidecar still doesnt work in console but that's expected i guess)

One thing is that if you select "nothing" and plot you get:
```python
x.plot(, "default", "default")
```

which obviously fails. We should catch this maybe and popup a message.

**Comment by sterlingbaldwin** [comment]
I added a check when the user hits plot, if they havent selected a variable I inject a comment into the console. I would rather do this in a toast message or something, but Im not sure how to access the jupyter notification system and this worked.

**Comment by doutriaux1** [comment]
@sterlingbaldwin feel free to merge

**Pull request merged**
