### PR TITLE
Linter fixes

### PR DESCRIPTION
**Pull request by downiec**
Completed a full review of all the source files and fixed all pertinent linting errors. Fixed minor bugs that I encountered when testing my fixes as well as the bug referenced in issue #98. This includes updates to the tslint.config as well as the package.json to improve the linting process and include dependencies that weren't previously included in the package.json (as pointed out by tslint). The challenge was updating all of the lambda expressions which required some modifications to the code itself (not just styling). I tested after each fix and seems that everything is working as before (and better). Also created a few new files in order to follow the convention of 1 class per file.

### CODE REVIEW

**Review by doutriaux1 — DISMISSED** [review]
On my linux box with firefox, I cannot save plots anymore, I get the following error:
```
Command ErrorCode resulted in errors. Error name: SyntaxError. Message: unexpected EOF while parsing (<ipython-input-10-707831e3c9d8>, line 1).
```

**Comment by doutriaux1** [comment]
@downiec on my mac, fresh env everything, I do not see the extension tab anymore and i get the following error:
```
JupyterLab build is suggested:
jupyter-vcdat needs to be included in build
@jupyterlab/hub-extension needs to be included in build


```

**Comment by downiec** [comment]
Tests for the export plot functionality and dimension sliders will be added in a separate PR
The save plots error has been fixed as well.

**Comment by doutriaux1** [comment]
@downiec once the pip issue is working let's merge this.

**Review by doutriaux1 — APPROVED** [review]
works perfectly for me. Good to go.

**Pull request merged**
