### PR TITLE
Check file existence

### PR DESCRIPTION
**Pull request by William-Hill**
Used sendSimpleKernelRequest() to check for the existence of the exported plot file.

### CODE REVIEW

**Review by downiec — COMMENTED** [review]
When I tested your branch, it seems like the export modal hangs until the plot is exported. Is that how it's supposed to work? Basically I didn't see the spinner anymore, just the final 'exported test.png' notification. Also it seems like sometimes the export success message shows up immediately (without waiting), before the plot is exported.

**Comment by William-Hill** [comment]
@downiec I added some of the fixes we discussed yesterday.  I added a slight delay but the file still takes a moment to show up in the Jupyter Lab UI.  I'll look at the Jupyter Lab Filebrowser code to try to use that to detect the new file instead of sending Python code to the kernel. But I'll create a separate PR for that as it may take more time.

**Comment by doutriaux1** [comment]
Thx @William-Hill !

**Review by doutriaux1 — APPROVED** [review]

**Comment by downiec** [comment]
@William-Hill Hey so I tested this branch and it looks like the delay between the file showing up in the browser is caused because jupyterlab wasn't refreshing the browser (which means you had to wait for the next auto-refresh interval). I worked on and added a fix that commands JupyterLab to refresh the file browser soon as the 'Exported plot.png' modal pops up. It looks like the export modal is working better now because there's practically no delay between clicking the export button, and seeing the new export in the filebrowser. Test it out and let me know what you think.

**Review by downiec — CHANGES_REQUESTED** [review]
With that last minor fix, I think it is ready for merging.

**Review by downiec — APPROVED** [review]

**Pull request merged**
