### PR TITLE
Loading screen for initial notebook setup

### PR DESCRIPTION
**Pull request by downiec**
Added a jupyterlab splash screen when first loading the notebook.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@downiec 
this is not going to work
remove your ${HOME}/.cdat launch jupyter-lab
now the full screen is covered with the jupyter logo
but in the back it is asking you about allowing anonymous
so it hangs forever
so what we need a just a little pop-up dialog window that says "loading CDAT core modules, please wait" with a close button

**Comment by downiec** [comment]
It was working great when I tested it, but I forgot about the ‘anonymous’ thing. Alright I can do the modal, unfortunately it just adds another thing the user has to click :/
That means 3 clicks just to start.. first error, then select kernel, then the loading notice

**Comment by doutriaux1** [comment]
@downiec if you can automatically close the dialog window once the module is imported then that does not add an extra click.

**Comment by downiec** [comment]
@doutriaux1 Yes I'll be making a custom modal so I can control when it opens/closes. I'll also add a timeout (since that was missing).

**Review by doutriaux1 — APPROVED** [review]
Awesome work!

**Pull request merged**
