### PR TITLE
Setup install

### PR DESCRIPTION
**Pull request by doutriaux1**
@sterlingbaldwin @downiec this is ready for review

### CODE REVIEW

**Comment by doutriaux1** [comment]
@sterlingbaldwin I think we will need to edit your section where you listen to hardcoded 5000 port for vcs-js server. But we might delete the need for it first 😉

**Comment by downiec** [comment]
It looks like it'll work good, I suggest we update the README to reflect any changes to the install/run process.

**Review by downiec — APPROVED** [review]
I think we should update the README to remove any unnecessary installation/run steps.

**Comment by doutriaux1** [comment]
@downiec good idea, I will update the readme.

**Pull request merged**
