### PR TITLE
Recognize vcs without metadata

### PR DESCRIPTION
**Pull request by downiec**
This update is an attempt to resolve issue #84, it allows vcdat to recognize variables, inject and plot etc. in a notebook that doesn't have meta data. For non-metadata notebooks, the code 'vcs.init()' is run and if no exception occurs, it assumes that vcs functionality can run in the notebook.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@downiec just to be sure it's working as intended.

I create a notebook using `jupyter-notebook` to be sure non of our stuff is in

cell code:
```
import cdms2
import MV2
a = MV2.ones((10,20))
```

Then I start `jupyter-lab` (with your branch), run the notebook, it does not see any variable. If I load a variable (`clt`) then they both appear. 
Should we add a "refresh" button or something so it shows the existing variables w/o loading another one?

**Comment by downiec** [comment]
@doutriaux1 Yes I wasn't sure what would be better to do in the situation of live code changing for a non-vcdat-notebook. The issue is that in order for it to automatically recognize a notebook with variables (as you're typing code in it), it would need to have an event listener always checking to see if the notebook has variables. I felt it would be a little intrusive for the extension to be doing that background work on any notebook, regardless of whether it's intended for vcdat. I can think of a few options we could do so that the user can specify they want to run vcdat in the notebook.

**Comment by downiec** [comment]
import MV2
a = MV2.ones((10,20))
I haven't seen that code used to create a variable before. Currently I was checking for variables by trying: vcs.init() in the notebook. If there's no error, I was assuming that the notebook was vcs ready and then I look for variables. What should I use to check that a notebook has variables and can do plotting etc? Is MV2 the thing I need to look for? Or a combination?

**Comment by doutriaux1** [comment]
the code i gave you before picks it up. But only *after* I load a variable through a file. So you do not need to change anything.

**Comment by downiec** [comment]
I updated this PR, so that any notebook can be set/initialized for use by VCS, the user simply clicks the 'Update' button and any necessary imports will be injected. The Update button is only shown in cases where the notebook needs to be initialized. The notebook will then be prepared and the variable list updated.

**Review by doutriaux1 — APPROVED** [review]

**Pull request merged**
