### PR TITLE
Variable tracker

### PR DESCRIPTION
**Pull request by downiec**
Adds a new VariableTracker class which contains the logic and data used for handling/maintaining variables. I added the use of Phosphor signals to several components so that their UI elements will update whenever a change occurs to specific data/variables in the VariableTracker and elsewhere. Overall improvement to maintainability, scalability and readability of code by increasing the separation of concern within the components. Lots of changes under the hood, did my best to test and make sure everything works as well or better than before however more tests by others would be helpful. Includes a fix for issue #107

### CODE REVIEW

**Comment by doutriaux1** [comment]
@downiec I played with it a bunch and it seems ok. One thing I found 
* open clt.nc
* load clt
* plot it
* change graphic method to isofill
* change template
* load u/v
* plot as vector
Plot appears in a second tab. (exporting plot does export from this one so it's "ok")

**Comment by doutriaux1** [comment]
I'm not sure this has anything to do with your branch, might be in master too.

**Comment by doutriaux1** [comment]
Actually on further investigation. To reproduce:
* everytime you load a variable from a file a new `canvas` is created in a new tab

I do think it's related to this branch

**Review by doutriaux1 — CHANGES_REQUESTED** [review]
WE need to fix the bug where the `canvas` object is re-created everytime you open a file

This leads to
* mutliple vcs canvas tabs
* probably memory leaks

**Comment by doutriaux1** [comment]
@downiec looks like the bug is also in master (please double check). So it might be ok to merge this and then submit another PR for the bug described. I'll submit a bug.

**Comment by downiec** [comment]
The issue you mention was already there before this PR, but I think I fixed it. I've added the fix to this PR

**Review by doutriaux1 — APPROVED** [review]

**Pull request merged**
