### PR TITLE
Tests update

### PR DESCRIPTION
**Pull request by muryanto1**
We now have the following classes with methods that testcases can call.

+ MainPageLocator class:
  - click_on_notebook_launcher
  - click_on_folder_tab
  - click_on_running_tab
  - click_on_command_palette_tab
  - click_on_vcdat_icon
  - click_on_open_tabs_tab
  - click_on_home_icon
  - click_on_jp_tool_bar_icon
  - click_on_new_launcher_icon
  - click_on_new_folder_icon
  - click_on_upload_files_icon
  - click_on_refresh_file_list_icon
  - click_on_select_kernel
  - shutdown_kernel
  - shutdown_all_kernels

+ LoadVariablesPopUp class:
  - click_on_variable
  - click_on_variable_axes
  - click_on_load
  - locate_all_axes_for_variable
  - locate_axis_with_title
  - adjust_var_axes_slider

+ VcdatPanel class:
  - click_on_plot
  - click_on_export_plot
  - click_on_clear
  - click_on_load_variables
  - select_a_plot_type
  - select_a_template
  - select_overlay_mode
  - deselect_overlay_mode
  - select_variable
  - deselect_variable
  - click_on_edit_button_for_variable

+ SavePlotPopUp class:
  - input_plot_file_name
  - select_export_format
  - click_on_export
  - select_custom_dimensions
  - deselect_custom_dimensions
  - click_on_custom_dimensions_unit
  - enter_unit_width
  - enter_unit_height
  - select_capture_provenance
  - deselect_capture_provenance

+ FileBrowser class:
  - double_click_on_a_file

+ NoteBookPage class:
  - new_notebook
  - get_notebook_name
  - rename_notebook
  - save_current_notebook
  - close_current_notebook

+ EditAxisPopUp class:
  - adjust_var_axes_slider
  - click_on_update

### CODE REVIEW

**Review by doutriaux1 — CHANGES_REQUESTED** [review]
@muryanto1 lots of conflicts with `master` can you resolve them please?

**Review by downiec — APPROVED** [review]

**Comment by downiec** [comment]
> @muryanto1 lots of conflicts with `master` can you resolve them please?

We resolved the merge conflicts.

**Review by doutriaux1 — APPROVED** [review]

**Comment by doutriaux1** [comment]
@downiec  somehow it failed in master

**Comment by downiec** [comment]
@doutriaux1  It was passing when I merged? What did you see?

**Comment by doutriaux1** [comment]
https://circleci.com/gh/CDAT/jupyter-vcdat/1068?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

and

https://github.com/CDAT/jupyter-vcdat/commits/master

**Pull request merged**
