### PR TITLE
Variables switching

### PR DESCRIPTION
**Pull request by downiec**
Contains code updates for the following:
* Merges the varLoader branch UI changes with the latest notebook_fixes
* Notebook switching correctly updates the sidebar variables list
* Removed need for python backend by running functions through a kernel request.
* Variable list refreshes and updates whenever user runs new code in a vcs ready notebook
* When running plot function, only up to 2 variables are passed
* Removed some variables in favor of an enum for tracking notebook state, and rewrote some functions to use that.

NOTE: The python backend related files and code haven't been removed yet, but they should no longer be needed. Maybe @sterlingbaldwin could remove the related files and code to clean that up and commit to this PR before it's merged? JupyterLab's 'serverextension' however IS needed for the github extension, if we plan on having that included: https://github.com/jupyterlab/jupyterlab-github#Installation

### CODE REVIEW

**Comment by sterlingbaldwin** [comment]
This is a big PR that will take some time to go through. Why do we want to pull in the Github labextension?

**Comment by downiec** [comment]
> This is a big PR that will take some time to go through. Why do we want to pull in the Github labextension?

I'm not sure why we need the Github lab extension included, I didn't add it and if none of the project depends on it I think it could be removed in my opinion.

**Comment by doutriaux1** [comment]
I added it originally, but we can remove it from here, it will only be on the docker images

**Review by sterlingbaldwin — APPROVED** [review]
Looks good to me.

**Pull request merged**
