### PR TITLE
Save netcdf file

### PR DESCRIPTION
**Pull request by William-Hill**
Addresses #104.  Added a modal to save a netCDF file with several toggle switches for activating options.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@William-Hill it seems like the install is broken, see: https://980-147574270-gh.circle-artifacts.com/0/home/circleci/project/jupyter-vcdat_logfile.txt

error:
```
src/components/VCSMenu.tsx(399,37): error TS2339: Property 'selectedVariables' does not exist on type 'Readonly<IVCSMenuState>'.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jupyter-vcdat@0.1.0 build: `tsc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jupyter-vcdat@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2019-05-18T00_38_37_528Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jupyter-vcdat@0.1.0 prepare: `npm run clean && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jupyter-vcdat@0.1.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2019-05-18T00_38_37_553Z-debug.log
Failed at 117: npm install
Trace:  117 0
return code:  0
```

**Comment by William-Hill** [comment]
@doutriaux1 I made a mistake when I rebased my branch on top of master.  Just pushed a commit to fix the bug.

**Comment by William-Hill** [comment]
@doutriaux1 I just pushed a commit to my PR to fixed the alert when saving a Variable.  In my testing, the save happens so quickly that the spinner doesn't show up and the successful export message shows up immediately.  It also goes away on its own after a delay

**Comment by doutriaux1** [comment]
@William-Hill works nice (the save part) thanks. But tests are failing.

**Review by doutriaux1 — DISMISSED** [review]
Please merge master in and see if it helps the tests. @downiec you might need to do the merge.

**Comment by doutriaux1** [comment]
@William-Hill circleci still fails

**Comment by William-Hill** [comment]
@doutriaux1 I fixed the errors caused by the merge into master.  The functionality of the PR works. The test now fails on test_select_plot_type.  It complains of a TargetOutOfBoundsException.
```
b'======================================================================'
b'ERROR: test_select_plot_type (test_plot_locators.TestPlot)'
b'----------------------------------------------------------------------'
b'Traceback (most recent call last):'
b'  File "/home/circleci/project/tests/test_plot_locators.py", line 42, in test_select_plot_type'
b'    vcdat_panel.click_on_plot()'
b'  File "/home/circleci/project/tests/PageObjects/VcdatPanel.py", line 50, in click_on_plot'
b'    self.move_to_click(element)'
b'  File "/home/circleci/project/tests/PageObjects/Actions.py", line 96, in move_to_click'
b'    ActionChains(self.driver).move_to_element(element).click().perform()'
b'  File "/home/circleci/project/workspace/test_firefox/miniconda/envs/jupyter-vcdat/lib/python3.7/site-packages/selenium/webdriver/common/action_chains.py", line 80, in perform'
b'    self.w3c_actions.perform()'
b'  File "/home/circleci/project/workspace/test_firefox/miniconda/envs/jupyter-vcdat/lib/python3.7/site-packages/selenium/webdriver/common/actions/action_builder.py", line 76, in perform'
b'    self.driver.execute(Command.W3C_ACTIONS, enc)'
b'  File "/home/circleci/project/workspace/test_firefox/miniconda/envs/jupyter-vcdat/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute'
b'    self.error_handler.check_response(response)'
b'  File "/home/circleci/project/workspace/test_firefox/miniconda/envs/jupyter-vcdat/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response'
b'    raise exception_class(message, screen, stacktrace)'
b'selenium.common.exceptions.MoveTargetOutOfBoundsException: Message: (57.5, -3.5) is out of bounds of viewport width (720) and height (466)'
```

I added a new button in this PR.  Could that be what's causing the test failure @muryanto1?

**Comment by doutriaux1** [comment]
@William-Hill I think you're right. @muryanto1 do you know how to fix this?
will take a look now.

**Comment by muryanto1** [comment]
@William-Hill, the problem is here:
b'  File "/home/circleci/project/tests/PageObjects/VcdatPanel.py", line 50, in click_on_plot'
b'    self.move_to_click(element)'

Try to replace the self.move_to_click(element) to:
self.scroll_click(element) in click_on_plot() method.

If that does not fix it, I can play with the branch.

**Comment by doutriaux1** [comment]
@William-Hill @muryanto1 do we know why this fails?

**Comment by muryanto1** [comment]
> @William-Hill @muryanto1 do we know why this fails?

Most likely it is due to the new button(s) that this PR is adding.
I am going to work on fixing the tests now, wanted to work on it last week, but ran into the conda issue (the corrupted checksum), and I was not able to create a conda environment to run this branch.

**Review by downiec — APPROVED** [review]

**Comment by doutriaux1** [comment]
@downiec I do not see the "rename" and "del" buttons, are they supposed to be here?

**Pull request merged**
