### PR TITLE
Add selenium tests

### PR DESCRIPTION
**Pull request by muryanto1**
added test_plot_variable1 test case -- load clt.nc, and plot it.
current .circleci/config.yml only launch tests when ran in linux_docker environment. and it only tests with chrome.
I am having difficulty to get the same test case to pass with firefox, but will look into it further.

### CODE REVIEW

**Comment by sterlingbaldwin** [comment]
This all looks good to me, I think we can merge it. The application is going to be going through some changes as far as where buttons are, so its probably a good idea to hold off on adding a bunch of selenium tests, but getting the infrastructure in is great.

**Comment by doutriaux1** [comment]
@sterlingbaldwin I think the idea was for you and @downiec to make sure the test still passes with your new interface, and ping @muryanto1 in order to make it work again.

**Comment by sterlingbaldwin** [comment]
@doutriaux1 @downiec Could you guys take a couple minutes to decide whats needed for this PR, its been open since January.

**Comment by muryanto1** [comment]
I am almost done updating my first testcase to work with 'next' branch. The test case loads a variable and plot. I am writing library routines that you can call when adding new testcases.

**Comment by muryanto1** [comment]
ok. I updated the test code to work with latest 'next' branch.
It loaded 'clt.nc', load 'clt' variable and plot.
I will add more testcases, but I want to get this in first, so at least it will get exercised.
I only built on macos and linux docker image, and I only run tests with chrome (on the linux-docker image).  I have a problem running the test case with firefox, need more time to debug.
I have lots of debugging print in the testcase, let me leave them there for now.
Let me know if I can merge.

**Review by downiec — APPROVED** [review]

**Review by doutriaux1 — APPROVED** [review]
@muryanto1 I would remove mac it sucks up too many credits

**Comment by muryanto1** [comment]
> @muryanto1 I would remove mac it sucks up too many credits

I removed mac.

**Pull request merged**
