### PR TITLE
Kube

### PR DESCRIPTION
**Pull request by doutriaux1**
setup.py seemed to mess the install. This branch cleans uo the setup.py and requires a bit more manual installs... Also take a look a dockerfiles in kube directory to see if we could shrink the images even more

### CODE REVIEW

**Comment by sterlingbaldwin** [comment]
Has this been tested?

**Comment by doutriaux1** [comment]
@sterlingbaldwin still tweaking it to get an optimal docker image. I'll ping you guys when it's ready for a full review.

**Comment by doutriaux1** [comment]
@William-Hill @sterlingbaldwin @downiec I think this is ready for review/merging

**Review by downiec — COMMENTED** [review]
Should this be integrated with William's changes to the install/README? And do you want to delete instead of commenting out the code?

**Comment by doutriaux1** [comment]
@downiec let's merge @William-Hill in first and see what happens

**Comment by doutriaux1** [comment]
@downiec @sterlingbaldwin @William-Hill this is ready to go in master. Please review the wiki page as well:

https://github.com/CDAT/jupyter-vcdat/wiki/Deploy

**Pull request closed without merging**
