### PR TITLE
Rename variable

### PR DESCRIPTION
**Pull request by downiec**
This is a large PR that contains several important changes in order to make renaming/copying of variables functional (issue #49):

- Variables now have an 'alias' which is a name given by the user for the variable so that loading a variable from a file will work correctly. Each variable keeps track of it's 'name' (original name in the file), and its 'alias' (the name that it was assigned after being loaded).
- Variables also have a unique 'varID', which is simply their name + alias.
- Added several search functions to varTracker for finding variables using either an alias or varID.
- Added checks to prevent and avoid variables with duplicate names, and other cases.
- Variables are now loaded in batches, rather than one variable per cell.
- Variables can now be deleted or copied, with necessary logic and validation to make sure notebook is in sync with the vcdat-widget
- The ability to rename a variable is now possible via the edit button in the varLoader modal.
- Added several validation steps to actively signal to users when a name is invalid or will cause issues.
- Did some clean-up of components by moving some common tasks over to varTracker, so that less code is repeated.
- When keeping track of selected variables, the whole variable is now stored, rather than just it's name. This allows the variable to be check for its original name, alias, ID or other information.
- Minor bug fixes I encountered along the way are also dealt with in this PR.
   - Finally fixed issue #81 so that dimension slider changes in the varMini modal won't select/deselect variables.
   - Noticed the dimension sliders in the varMini are twitchy, removed a css overflow property that was causing the issue.

### CODE REVIEW

**Review by doutriaux1 — APPROVED** [review]
@downiec I'm not sure if it's something we need to change, the first time I tried it I did not "click" on the rename button so the variable cam in with its regular name. Should we remove this need? i.e if any valid input is in the box use it as the final name. Then maybe replace the "rename" button with "reset" (to original name)? Maybe we can implement this later (after the release)

**Comment by doutriaux1** [comment]
@downiec tests are failing, I sshed into the machine and import cdms2 works, so it's a real failure

**Comment by downiec** [comment]
@doutriaux1  I will try to find out what is failing. As far as the rename variables button.. removing a click means the user won't have a chance to confirm their choice and get the feedback message if there are issues. I can look into alternatives but I think it would be good to get user feedback first because some people might prefer to have the button so they can 'confirm' their choice. I understand what you mean though as I also forgot to push the button sometimes (mainly because I was just in a hurry testing things).

**Comment by downiec** [comment]
@doutriaux1 I think I know what the failure is. I changed the name of the 'axis' button, to 'edit' so the selenium test couldn't find the slider button.

**Pull request merged**
