### PR TITLE
Adds the VarMini which is a much smaller version of the VarCard but w…

### PR DESCRIPTION
**Pull request by sterlingbaldwin**
…ith the same functionality

### CODE REVIEW

**Comment by sterlingbaldwin** [comment]
WORK IN PROGRESS DO NOT MERGE.

**Comment by sterlingbaldwin** [comment]
This is ready for review.

**Review by downiec — APPROVED** [review]

**Comment by downiec** [comment]
Looks good to me, but it has some merge conflicts with the latest next branch which should be resolved before it's merged.

**Comment by doutriaux1** [comment]
@sterlingbaldwin I was just sitting with @William-Hill and we run into a case that we cannot handle here, William was pltting (manually)
```
canvas.plot(v,v,"default","default")
```
And indeed in the current schema we cannot select the same variable twice

Also I was wondering why we are limiting ourselves to two variables. Could be have *unlimited* selection? with the labels next to them being "1", "2", "3", etc....

**Comment by downiec** [comment]
We set the limit to 2 because if we let it be unlimited then the injections fail when you try something like: canvas.plot(clt, u, v, clt2, "default", "default")
I remember that you mentioned we only need to handle 2 for now, so I set that as a constant. It can be changed to 3 or 4 etc. when that limite changes

**Comment by doutriaux1** [comment]
I was looking at the code with @William-Hill just now and it seems that the selection gets truncated to 2 if ore than two.

**Comment by doutriaux1** [comment]
@sterlingbaldwin I have to click exactly on the varialbe name to select/unselect it, could you make it such as i can click anywhere on the line.
It's just a detail I'm still going to approve this

**Comment by doutriaux1** [comment]
@sterlingbaldwin there's merge conflcit BTW and also I get errors on Linux when trying to open ANY file.

**Comment by doutriaux1** [comment]
@sterlingbaldwin the *Linux* error is on every branch just not yours, mostly curious to know if it works for you

**Review by doutriaux1 — APPROVED** [review]
would like to be able to select more than 2 (for future funcs) and being able to click on the line anywhere

**Comment by downiec** [comment]
> I was looking at the code with @William-Hill just now and it seems that the selection gets truncated to 2 if ore than two.

Yes, that was part of an update

**Review by downiec — APPROVED** [review]

**Pull request merged**
