### PR TITLE
Getting started notebook

### PR DESCRIPTION
**Pull request by davis278**
Adding two new folders: docs and docs/notebooks so there is a place to put the getting_started.ipynb file.

### CODE REVIEW

**Comment by davis278** [comment]
@doutriaux1 when you are available, we need to talk about what else you'd like to add to this getting started Jupyter notebook.  It would be great if the notebook could exist in the directory from which JupyterLab is launched. 

One test that has not been completed yet is to see how a few of the commands work within the JupyterLab environment. Jason and I tested in a Jupyter Notebook environment, and are hoping that it will work more seemlessly in the JupyterLab environment (i.e. the kernels will be managed better).

**Comment by doutriaux1** [comment]
@davis278 

***Storage*** section depends on system deployed, we can't know, might be better to update the dedicated wiki pages for aims1/crunchy

***Software*** section

Currently `jupyter-vcdat` brings in: `nodejs "python>3" vcs jupyterlab pip nb_conda nb_conda_kernels plumbum jupyterhub` . by default

Again our installations bring in more:

crunchy as the whole `cdat` installation (that means pkg suck as `vcsaddons` `thermo` `wk`, etc....

***Conda*** Section

```
You have access to conda as a software management tool.

**NOTE: Anything installed in the [base] conda environment will not persist between sessions.**
```

The above is only true for kubernetes-deployed version
 Maybe [snip] the `conda` list output sections it's long and not very relevant here.

We should link back to wiki both at top and bottom.

We should add [this page](https://github.com/CDAT/jupyter-vcdat/wiki/Load-Variables) into this notebook along with [this download sample_data section](https://github.com/CDAT/jupyter-vcdat/wiki/Access-Data)

**Review by doutriaux1 — CHANGES_REQUESTED** [review]
@davis278 see my comments on the conversation page.

**Comment by doutriaux1** [comment]
@davis278 could we finish this one today? The storage option I think we could copy/paste your link that explain how to get sample data and most importantly (probably should be first) the bit explaining symlinking to your home directory. Probably should mention CDAST can open any opendap file. And point back ESGF page to search/download/get dap url for datasets.

Not sure what you had in mind for "software options" but we could mention that by default it comes with:

- python >3
- cdat_info
- genutil
- dv3d
- libcdms >=3.1.2
- vtk-cdat >8.1
- cdms2
- cdutil
- requests
- numpy
- ghostscript

**Comment by davis278** [comment]
@doutriaux1 I've added some text and made some other edits to this notebook. If you are OK with those changes, this branch can be merged into master.

**Review by doutriaux1 — APPROVED** [review]
Thanks @davis278

**Comment by davis278** [comment]
@doutriaux1 per our conversations this morning, I've moved the adding environments in JupyterHub part of the notebook to a new add_envs_in_hub.ipynb notebook. That new notebook works fine on a single computer but is not yet working on acme1 or crunchy so I have not included that notebook in this pull request yet. I have pushed the changes to the getting_started.ipynb notebook however and if you are OK with the changes, I can merge with master.

**Pull request merged**
